name: bait-environment
channels:
- menpo
dependencies:
- python=2.7
- ffmpeg
- pip
- pip:
  - PySide
  - clique
  - lucidity
  - pyperclip
- git:
  - https://bitbucket.org/tokejepsen/QtExt.git
  - https://bitbucket.org/ftrack/ftrack-connect.git
  - https://bitbucket.org/tokejepsen/ftrack-connect-maya.git
  - https://bitbucket.org/ftrack/ftrack-connect-foundry.git
  - https://bitbucket.org/ftrack/ftrack-connect-nuke.git
  - https://github.com/tokejepsen/ftrack-hooks.git
  - https://github.com/tokejepsen/ftrack-locations.git
  - https://github.com/tokejepsen/ftrack-template.git
  - https://github.com/pyblish/pyblish-base.git
  - https://github.com/bumpybox/pyblish-bumpybox.git
  - https://github.com/pyblish/pyblish-ftrack.git
  - https://github.com/tokejepsen/pyblish-deadline.git
  - https://github.com/pyblish/pyblish-houdini.git
  - https://github.com/tokejepsen/pyblish-standalone.git
  - https://github.com/tokejepsen/pyblish-aftereffects.git
  - https://github.com/pyblish/pyblish-nuke.git
  - https://github.com/pyblish/pyblish-hiero.git
  - https://github.com/pyblish/pyblish-lite.git
  - https://github.com/pyblish/pyblish-maya.git
  - https://github.com/tokejepsen/ftrack-connect-environment.git:
    - python $REPO_PATH/environment.py
  - https://github.com/tokejepsen/bait-environment.git:
    - python $REPO_PATH/environment.py
    - python -m ftrack_connect
